### ISSUE TITLE
panic runtime error index out of range [1] with length 1

### ISSUE THREAD

**Issue by CartCaved** [digitalocean/pgremapper#14]
**Background information:**
Since there are no releases, I'm am basing this issue on having tried to follow the build instructions. The result of the docker method and the result of the go method produced different sized binaries, but both seem to have the same issue.

**Issue**
When running pgremapper with different commands (pgremapper cancel-backfill --verbose, pgremapper export-mappings --verbose 12, pgremapper drain 12 --verbose), the binary fails with very similar output:
```
** executing: ceph osd dump -f json
** executing: ceph pg dump pgs_brief -f json
** executing: ceph osd dump -f json
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
main.computeBackfillSrcsTgts(0xc00277b10) (export mapings) - or (0xc0025dc58) (cancel-backfill), (0xc00277c28) (drain)
< trace into different modules >
```
I know very little about Go so I don't where to start troubleshooting the issue.

**Comment by CartCaved** [comment]
Hi! I was hoping to avoid that since the ceph cluster is on an offline, secure system.. But I have initiated the process to transfer the files with the outputs and should have them available tomorrow. I did try running export-mappings on a second ceph cluster (with no backfilling operations running) and it seemed to work, so I'm sure you're right about the messy cluster being in an unusual state.

Thanks!

**Comment by CartCaved** [comment]
Huh, this is quite strange. Both OSD 64 and 38 are up and in, 34 is up and out (being drained). 

Wait, the issue is that 64 is both up_primary and acting_primary. Or, that 64 is up but not 38 and 24 (which are also up, even if 34 is out). 

Is there anything I can do to get you more information?

And is there anything I can do about that pg?!

**Comment by baergj** [comment]
The issue is that the up set should have 3 members, but it has 1.

Looking deeper, that's the only PG in that pool (pool 1). Should that pool even exist?
