### ISSUE TITLE
cancel-backfill distinguish between source and target

### ISSUE THREAD

**Issue by stuartthebruce** [digitalocean/pgremapper#25]
It would be nice if `cancel-backfill` could distinguish between source and target, e.g., for a nearly full OSD cancel backfill for which it is a target but not a source.

**Comment by baergj** [comment]
@stuartthebruce That sounds look a good idea. To be clear, do you mean something like this?
```bash
$ ./pgremapper cancel-backfill --target-osds 42
```
Which would cancel any backfills targeting OSD 42?

**Comment by baergj** [comment]
My apologies for the late response - apparently I don't get notifications for emojis added to posts! Thanks for confirming. Not sure when we'll get to this but contributions are always welcome. :)

**Comment by BenoitKnecht** [comment]
Now that #37 has been merged, this issue can be closed, right?

**Comment by baergj** [comment]
Correct, thanks! Fixed by #37.
