### ISSUE TITLE
Install instructions

### ISSUE THREAD

**Issue by jelka71** [digitalocean/pgremapper#30]
After Go v1.17 the "go get github.com/digitalocean/pgremapper" install command is deprecated, which means it goes not work in e.g. Rocky Linux 8 using Go from standard repo. 
I managed to install by running: 

```
git clone https://github.com/digitalocean/pgremapper
cd pgmapper
go build -o /usr/local/bin
```

This installed pgremapper in /usr/local/bin

Best, Jesper

**Comment by baergj** [comment]
Thanks for reporting this! I think the new way is actually `go install github.com/digitalocean/pgremapper@latest`; I'll make a note to update the docs.
