### ISSUE TITLE
detect a given pg belongs to an ec pool

### ISSUE THREAD

**Issue by microyahoo** [digitalocean/pgremapper#33]
Hi @xvillaneau, @baergj, I noticed that when detect whether it is an EC pool, it is only to identify whether the ec profile is equal to `replicated_rule`, AFAIK, the ec profile can be any string value. So we can detect a ec pool if its ec profile is not null. Any comments are welcome, thanks.
https://github.com/digitalocean/pgremapper/blame/main/ceph.go#L304

**Comment by baergj** [comment]
Good catch!
