### ISSUE TITLE
permit drain command to take multiple source OSDs

### ISSUE THREAD

**Issue by robbat2** [digitalocean/pgremapper#40]
Please permit the drain command to take multiple source OSDs, ideally with an osdspec.

Desired usage:
`$ pgremapper drain bucket:rack-A --target-osds bucket:rack-B`

Right now this can be emulated with one run per source OSD, but that means data-collection on each pass

**Comment by baergj** [comment]
Hi Robin! :wave: 

This sounds reasonable, but I'll think about it a bit once I get some headspace. IIRC there was a reason why I didn't do this in the first place, so I need to look through the implementation to reload my memory

**Comment by baergj** [comment]
I had a chance to look through the code this morning. I think this should be possible to implement if `calcPgMappingsToDrainOsd()` is change to round-robin across a set of source OSDs, recalculating the `candidateMappings` each time, until no source OSD has a successful remap.

If we didn't care about fairness we could instead run `calcPgMappingsToDrainOSD()` for each given source OSD. This is simpler and more efficient than the above approach, and might be OK assuming that the user is providing reasonable limits on source backfills scheduled.

As always, patches welcome, but I'll also put something on our backlog for this!

**Comment by baergj** [comment]
https://github.com/digitalocean/pgremapper/pull/41 will address this.

**Comment by DanWritesCode** [comment]
🫡  Hey Robin

This has been merged into main now. Let us know how it works when you try it.
