### ISSUE TITLE
remap: panic on source osd missing from up set

### ISSUE THREAD

**Issue by Matt1360** [digitalocean/pgremapper#47]
When the cluster is not in a happy state, and the source OSD is not in the up set, `pgremapper remap` will panic, preventing the user from trying to reconstruct data from a down OSD on a specific target.

**Comment by k0ste** [comment]
Some years ago, `pgremapper` have many of panics, see https://github.com/digitalocean/pgremapper/issues/10#issuecomment-945648879
Today, the master code works for us in every-day usage. So, if you think you find the new bug, lease read, how to [Bug Reports](https://github.com/digitalocean/pgremapper?tab=readme-ov-file#bug-reports)

For a quick fix you can use this shell function

```bash
function fix_pgremapper_panic() {
  # function fix situations when pgremapper is crashed on some osdmaps
  local pg
  local upmap_cmd
  upmap_cmd="--verbose"

  if [[ -n "${UPMAP_POOL}" ]]
    then
      upmap_cmd="${upmap_cmd} --include-pools ${UPMAP_POOL}"
  fi

  # shellcheck disable=SC2086
  until ${PG_REMAPPER} cancel-backfill ${upmap_cmd} > /dev/null 2>&1
    do
      pg="$(${PG_REMAPPER} cancel-backfill ${upmap_cmd} 2>&1 >/dev/null | \
        grep "panic" | tr -d '\n' | awk '{print $3}' | sed 's|:||g')"
      echo -e "Fix pgremapper panic for PG ${pg}"
      ceph osd rm-pg-upmap-items "${pg}"
      sleep 1s
    done
}
```

**Comment by baergj** [comment]
Thanks @k0ste! @Matt1360 is actually one of the pgremapper devs; we noticed this issue last week and wanted to make sure we didn't lose track of it.
