### ISSUE TITLE
Cancel-backfill not progressing

### ISSUE THREAD

**Issue by torkilt** [digitalocean/pgremapper#51]
Hi

I haven't used the tool before but was pointed here from the mailing list[1]. Not sure if I am just misunderstanding something but cancel-backfill seems to be unable to do any more after taking misplaced down from ~29% to 12.8% the first time I ran it. Running it repeatedly doesn't remove any more of the PGs in backfill or backfill_wait.

Command run: 

`
./pgremapper cancel-backfill --yes --verbose |tee /tmp/pgremapper.out
`

Current status:

`
[root@lazy ~]# ceph -s
  cluster:
    id:     8ee2d228-ed21-4580-8bbf-0649f229e21d
    health: HEALTH_WARN
            1 failed cephadm daemon(s)
            nobackfill,norecover,noscrub,nodeep-scrub flag(s) set
            Degraded data redundancy: 1/3169196434 objects degraded (0.000%), 1 pg degraded, 3 pgs undersized
 
  services:
    mon: 5 daemons, quorum lazy,jolly,happy,dopey,sleepy (age 3d)
    mgr: jolly.tpgixt(active, since 3d), standbys: dopey.lxajvk, lazy.xuhetq
    mds: 1/1 daemons up, 2 standby
    osd: 540 osds: 539 up (since 21h), 539 in (since 5d); 2321 remapped pgs
         flags nobackfill,norecover,noscrub,nodeep-scrub
 
  data:
    volumes: 1/1 healthy
    pools:   15 pools, 10849 pgs
    objects: 547.16M objects, 1.1 PiB
    usage:   1.9 PiB used, 2.3 PiB / 4.2 PiB avail
    pgs:     1/3169196434 objects degraded (0.000%)
             405492775/3169196434 objects misplaced (12.795%)
             8525 active+clean
             2242 active+remapped+backfill_wait
             76   active+remapped+backfilling
             3    active+recovering
             2    active+recovering+undersized+remapped
             1    active+recovery_wait+undersized+degraded+remapped
 
  io:
    client:   14 MiB/s rd, 82 MiB/s wr, 817 op/s rd, 165 op/s wr
`

[ceph.pg.dump.pgs_brief.txt](https://github.com/digitalocean/pgremapper/files/14769730/ceph.pg.dump.pgs_brief.txt)
[ceph.osd.tree.txt](https://github.com/digitalocean/pgremapper/files/14769732/ceph.osd.tree.txt)
[ceph.osd.dump.txt](https://github.com/digitalocean/pgremapper/files/14769733/ceph.osd.dump.txt)
[pgremapper.out.txt](https://github.com/digitalocean/pgremapper/files/14769734/pgremapper.out.txt)

[1] https://lists.ceph.io/hyperkitty/list/ceph-users@ceph.io/thread/BI5BXPQE5UJZBXUH5KZSVWQKYHMUKO7J/

**Comment by torkilt** [comment]
On second thought it might just be working as intended. Some of the changes I made to crush would require different placement and current placement would be invalid?

1) Added 4 hosts to a datacenter bucket (current placement ok)
2) Moved one host from one datacenter bucket to another (current placement invalid?)
3) Changed the failure domain for an EC pool from host to datacenter (current placement invalid?)

**Comment by baergj** [comment]
Hey @torkilt, yeah, based on that sequence I would expect you're hitting a condition where Ceph will not allow upmaps to override CRUSH placement

**Comment by torkilt** [comment]
Thanks for the confirmation, and the tool!
