### ISSUE TITLE
drain for source osdspec idea

### ISSUE THREAD

**Issue by k0ste** [digitalocean/pgremapper#9]
What we have:
* full upmap balanced cluster
* need to redeploy OSD host (full host): out -> purge -> deploy -> fill
* pgremapper drain can drain only OSD's, not osdspec

Can we achieve this currently:

* `ceph osd crush reweight-subtree 0`
* `for e 'in ceph osd df tree name host1.example.com | grep osd\. | awk '{ print $1}'' ; do ceph osd out osd.${e} ; done`
* balance:
```python
ceph osd getmap -o osd.map
osdmaptool osd.map \
  --upmap-deviation 1 \
  --upmap-max 10000 \
  --upmap upmap.sh | sh
```

How we look the flow - one commad

```python
pgremapper drain bucket:host1.example.com
```

This issued (may be not all steps, can be scripted):
* `ceph osd crush reweight-subtree 0`
* `ceph osd out for this subtree`
* make upmaps to another buckets to respect crush rule

What do you think?

**Comment by baergj** [comment]
Hey there,

Thanks for the suggestion!

pgremapper is intended to manipulate only the upmap exception table, and I'd rather it stay that way for now. Although not universally true, we avoid marking things `out` as much as possible, as doing so makes it difficult to control backfill scheduling (another reason for pgremapper's current existence and design). FWIW, the way that I would accomplish what you're trying to do here with pgremapper today would be to CRUSH-reweight the OSDs on the host to something approaching zero (e.g. 0.0001), then issue `pgremapper cancel-backfill` to undo the majority of the data movements, then finally run `pgremapper undo-upmaps` against the host being drained in a loop until fully drained. This way, we rely on CRUSH completely to reschedule where the PGs should go, and use pgremapper to control backfill scheduling. (We've done this before in various forms, FWIW.)

After recreating the OSDs on the host, I would then weight the OSDs back to full weight, and repeat the above process, though now I would probably use the standard upmap balancer to fill that host back in.

**Comment by k0ste** [comment]
@baergj thanks
Yes, we know that this should works, but it's doesn't :D 
May be this a bug of 14.2.19, because we just make on another, 14.2.22 cluster

```
ceph osd crush reweight osd.508 0
```
rebalance started without out, yes!

```
cancel-backfill --yes
```

And now remapped only 62 PG's, because osd.508 server 62 PG's

On next week we update 'problem' cluster to 14.2.22 and test this again

**Comment by baergj** [comment]
To be clear, Ceph acts differently if the weight is 0 as opposed to near-0. When it's zero, we've found that Ceph prevents upmaps that maps PGs to that OSD. It's possible this behaviour changed between versions.

Also, the appropriate approach depends on your CRUSH rule.. Ideally, you would leave the CRUSH weight alone and use an OSD reweight instead to avoid too much data shuffling.

**Comment by k0ste** [comment]
This was local single cluster issue, so I close this
